-- Seeds CMS content (customer.pages / customer.page_attributes) for the public marketing site.
-- Idempotent: re-running this script replaces all attributes for the pages listed below with
-- the values in this file. Safe to run repeatedly while there is no admin CRUD UI yet.
--
-- Arabic values are placeholder Modern Standard Arabic translations drafted to make the
-- language toggle work end-to-end; replace with reviewed copy before this ships to real users.

SET NOCOUNT ON;
BEGIN TRANSACTION;

-- 1) Ensure all pages exist (Global already exists in a fresh MiskBeirutDb)
MERGE customer.pages AS target
USING (VALUES
    (N'Global',  NULL, NULL, NULL),
    (N'Home',    N'Misk Beirut | High-Luxury Mediterranean Hospitality', N'Where heritage meets culinary excellence in Beirut.', N'misk beirut, lebanese restaurant, beirut dining'),
    (N'About',   N'About Us | Misk Beirut', N'A timeless sanctuary of Levantine hospitality.', N'about misk beirut, our story, elias mansour'),
    (N'Careers', N'Careers | Misk Beirut', N'Join a team dedicated to redefining Mediterranean hospitality.', N'careers, jobs, misk beirut'),
    (N'Contact', N'Contact Us | Misk Beirut', N'Get in touch with Misk Beirut for reservations and inquiries.', N'contact, reservations, misk beirut'),
    (N'Events',  N'Events | Misk Beirut', N'Experience unforgettable moments with us at Misk Beirut.', N'events, private events, misk beirut'),
    (N'Spaces',  N'Our Spaces | Misk Beirut', N'A place for every moment - from long dinners to quiet mornings.', N'our spaces, venues, misk beirut')
) AS src(PageName, MetaTitle, MetaDesc, MetaKeyword)
ON target.PageName = src.PageName
WHEN MATCHED THEN UPDATE SET MetaTitle = src.MetaTitle, MetaDesc = src.MetaDesc, MetaKeyword = src.MetaKeyword
WHEN NOT MATCHED THEN INSERT (PageName, MetaTitle, MetaDesc, MetaKeyword)
    VALUES (src.PageName, src.MetaTitle, src.MetaDesc, src.MetaKeyword);

-- 2) Clear existing attributes for these pages (idempotent reseed)
DELETE pa
FROM customer.page_attributes pa
JOIN customer.pages p ON p.Id = pa.PageId
WHERE p.PageName IN (N'Global', N'Home', N'About', N'Careers', N'Contact', N'Events', N'Spaces');

DECLARE @en INT = (SELECT Id FROM customer.languages WHERE Code = 'en');
DECLARE @ar INT = (SELECT Id FROM customer.languages WHERE Code = 'ar');
DECLARE @Global INT = (SELECT Id FROM customer.pages WHERE PageName = N'Global');
DECLARE @Home INT = (SELECT Id FROM customer.pages WHERE PageName = N'Home');
DECLARE @About INT = (SELECT Id FROM customer.pages WHERE PageName = N'About');
DECLARE @Careers INT = (SELECT Id FROM customer.pages WHERE PageName = N'Careers');
DECLARE @Contact INT = (SELECT Id FROM customer.pages WHERE PageName = N'Contact');
DECLARE @Events INT = (SELECT Id FROM customer.pages WHERE PageName = N'Events');
DECLARE @Spaces INT = (SELECT Id FROM customer.pages WHERE PageName = N'Spaces');

-- 3) Global (nav / footer / brand) --------------------------------------------------------
INSERT INTO customer.page_attributes (PageId, AttributeName, AttributeType, LangId, Value) VALUES
(@Global, N'brand_name', 'Text', @en, N'MISK BEIRUT'),
(@Global, N'brand_name', 'Text', @ar, N'مسك بيروت'),
(@Global, N'logo_image', 'Image', @en, N'/img/logo.png'),
(@Global, N'logo_image', 'Image', @ar, N'/img/logo.png'),
(@Global, N'nav_home', 'Text', @en, N'Home'),
(@Global, N'nav_home', 'Text', @ar, N'الرئيسية'),
(@Global, N'nav_about', 'Text', @en, N'About Misk'),
(@Global, N'nav_about', 'Text', @ar, N'عن مسك'),
(@Global, N'nav_spaces', 'Text', @en, N'Our Spaces'),
(@Global, N'nav_spaces', 'Text', @ar, N'أجواؤنا'),
(@Global, N'nav_menu', 'Text', @en, N'Menu'),
(@Global, N'nav_menu', 'Text', @ar, N'قائمة الطعام'),
(@Global, N'nav_events', 'Text', @en, N'Events'),
(@Global, N'nav_events', 'Text', @ar, N'المناسبات'),
(@Global, N'nav_contact', 'Text', @en, N'Reservations'),
(@Global, N'nav_contact', 'Text', @ar, N'الحجوزات'),
(@Global, N'footer_nav_title', 'Text', @en, N'Navigation'),
(@Global, N'footer_nav_title', 'Text', @ar, N'روابط'),
(@Global, N'footer_connect_title', 'Text', @en, N'Connect'),
(@Global, N'footer_connect_title', 'Text', @ar, N'تواصل معنا'),
(@Global, N'footer_careers_label', 'Text', @en, N'Careers'),
(@Global, N'footer_careers_label', 'Text', @ar, N'الوظائف'),
(@Global, N'footer_follow_title', 'Text', @en, N'Follow Us'),
(@Global, N'footer_follow_title', 'Text', @ar, N'تابعونا'),
(@Global, N'footer_visit_title', 'Text', @en, N'Ready to Visit?'),
(@Global, N'footer_visit_title', 'Text', @ar, N'جاهز للزيارة؟'),
(@Global, N'footer_cta_label', 'Text', @en, N'Reserve a Table'),
(@Global, N'footer_cta_label', 'Text', @ar, N'احجز طاولة'),
(@Global, N'footer_phone', 'Text', @en, N'+961 1 234 567'),
(@Global, N'footer_phone', 'Text', @ar, N'+961 1 234 567'),
(@Global, N'footer_email', 'Text', @en, N'concierge@miskbeirut.com'),
(@Global, N'footer_email', 'Text', @ar, N'concierge@miskbeirut.com'),
(@Global, N'copyright_name', 'Text', @en, N'Misk Beirut'),
(@Global, N'copyright_name', 'Text', @ar, N'مسك بيروت'),
(@Global, N'copyright_suffix', 'Text', @en, N'All rights reserved.'),
(@Global, N'copyright_suffix', 'Text', @ar, N'جميع الحقوق محفوظة.'),
(@Global, N'social_instagram_url', 'Link', @en, N'#'),
(@Global, N'social_instagram_url', 'Link', @ar, N'#'),
(@Global, N'social_facebook_url', 'Link', @en, N'#'),
(@Global, N'social_facebook_url', 'Link', @ar, N'#');

-- 4) Home ----------------------------------------------------------------------------------
INSERT INTO customer.page_attributes (PageId, AttributeName, AttributeType, LangId, Value) VALUES
(@Home, N'hero_image', 'Image', @en, N'https://lh3.googleusercontent.com/aida-public/AB6AXuBk0plMgb1g9EiKBfiJ_w7OfeWYJyvxPRduMltuI77vrXzTOcxZKxlksbUDZkNLBwiwtUIHoQMcEfvL0vY-iEGXbSOZEpzZ5tmmCnhLNeDwqV-Djx4j1Af8ic7nYPoqZvdv2e6nk1WToioNoh1Q585d9XjIO2ySbMEqqQk-MwdGdjFb4w1tkSH48xAxOC4v5V2n8NkxHH5T1C6GJkWOkq7gKi_i_slmIdRb3CFcQKKTtoKJ0JuUAVCRSosNfa6zYPEv-I78l5bqY3k'),
(@Home, N'hero_image', 'Image', @ar, N'https://lh3.googleusercontent.com/aida-public/AB6AXuBk0plMgb1g9EiKBfiJ_w7OfeWYJyvxPRduMltuI77vrXzTOcxZKxlksbUDZkNLBwiwtUIHoQMcEfvL0vY-iEGXbSOZEpzZ5tmmCnhLNeDwqV-Djx4j1Af8ic7nYPoqZvdv2e6nk1WToioNoh1Q585d9XjIO2ySbMEqqQk-MwdGdjFb4w1tkSH48xAxOC4v5V2n8NkxHH5T1C6GJkWOkq7gKi_i_slmIdRb3CFcQKKTtoKJ0JuUAVCRSosNfa6zYPEv-I78l5bqY3k'),
(@Home, N'hero_title', 'Text', @en, N'Welcome to Misk Beirut'),
(@Home, N'hero_title', 'Text', @ar, N'أهلاً بكم في مسك بيروت'),
(@Home, N'hero_subtitle', 'Text', @en, N'Where heritage meets culinary excellence'),
(@Home, N'hero_subtitle', 'Text', @ar, N'حيث يلتقي التراث بالتميز في فن الطهي'),
(@Home, N'hero_cta_reserve_label', 'Text', @en, N'Reserve a Table'),
(@Home, N'hero_cta_reserve_label', 'Text', @ar, N'احجز طاولة'),
(@Home, N'hero_cta_discover_label', 'Text', @en, N'Discover Misk'),
(@Home, N'hero_cta_discover_label', 'Text', @ar, N'اكتشف مسك'),
(@Home, N'about_image', 'Image', @en, N'https://lh3.googleusercontent.com/aida-public/AB6AXuDPzt89bFCPorHZemKwIfi48TgN5a19ZcfWGqzi1jX9c_N_0rIEnuUOhpnA77y5P1XNiVxM036yGmMlreCR4zzTks3JewaXxQWMmd9PlVpIAW7kiSficYMU3qMstRD8M5v6xFaLoTHMvLBCsh_HI52IGzUSkl0X4wUfpRUY36QAttHphl8TplHR5gpd_HxPXsUh9JJYnzhKH_xR85TvrCmH4vSR0UmLNJ_A2HoJaUAt_e1bEzHjGEV3w86-qtQozuF3u3kiV8wWi3A'),
(@Home, N'about_image', 'Image', @ar, N'https://lh3.googleusercontent.com/aida-public/AB6AXuDPzt89bFCPorHZemKwIfi48TgN5a19ZcfWGqzi1jX9c_N_0rIEnuUOhpnA77y5P1XNiVxM036yGmMlreCR4zzTks3JewaXxQWMmd9PlVpIAW7kiSficYMU3qMstRD8M5v6xFaLoTHMvLBCsh_HI52IGzUSkl0X4wUfpRUY36QAttHphl8TplHR5gpd_HxPXsUh9JJYnzhKH_xR85TvrCmH4vSR0UmLNJ_A2HoJaUAt_e1bEzHjGEV3w86-qtQozuF3u3kiV8wWi3A'),
(@Home, N'about_eyebrow', 'Text', @en, N'Since 1982'),
(@Home, N'about_eyebrow', 'Text', @ar, N'منذ عام 1982'),
(@Home, N'about_title', 'Text', @en, N'Our Story'),
(@Home, N'about_title', 'Text', @ar, N'قصتنا'),
(@Home, N'about_body', 'RichText', @en, N'Misk Beirut began as a humble family kitchen in the heart of the Levant, driven by a singular vision: to preserve the soul of Mediterranean hospitality while elevating it for the modern epicurean. Today, we stand as a beacon of luxury, where every ingredient is sourced with editorial precision and every recipe tells a story of generational mastery.'),
(@Home, N'about_body', 'RichText', @ar, N'بدأ مسك بيروت كمطبخ عائلي متواضع في قلب بلاد الشام، مدفوعاً برؤية واحدة: الحفاظ على روح الضيافة المتوسطية مع الارتقاء بها لتناسب ذائقة العصر الحديث. واليوم، نقف كمنارة للفخامة، حيث يُختار كل مكوّن بدقة متناهية، وتروي كل وصفة حكاية إتقان توارثته الأجيال.'),
(@Home, N'about_pillar_1_label', 'Text', @en, N'Heritage'),
(@Home, N'about_pillar_1_label', 'Text', @ar, N'التراث'),
(@Home, N'about_pillar_2_label', 'Text', @en, N'Quality'),
(@Home, N'about_pillar_2_label', 'Text', @ar, N'الجودة'),
(@Home, N'about_pillar_3_label', 'Text', @en, N'Community'),
(@Home, N'about_pillar_3_label', 'Text', @ar, N'المجتمع'),
(@Home, N'about_quote', 'Text', @en, N'"An honest approach to food, focusing on the integrity of ingredients and the warmth of Lebanese tradition."'),
(@Home, N'about_quote', 'Text', @ar, N'"نهجٌ صادق تجاه الطعام، يركّز على نقاء المكوّنات ودفء التقاليد اللبنانية."'),
(@Home, N'about_cta_label', 'Text', @en, N'Learn More About Us'),
(@Home, N'about_cta_label', 'Text', @ar, N'اعرف المزيد عنا'),
(@Home, N'menu_title', 'Text', @en, N'A Taste of Misk'),
(@Home, N'menu_title', 'Text', @ar, N'طعم مسك'),
(@Home, N'menu_subtitle', 'Text', @en, N'Discover our curated selection of Mediterranean cuisine, expertly prepared with the finest ingredients.'),
(@Home, N'menu_subtitle', 'Text', @ar, N'اكتشف تشكيلتنا المختارة من المأكولات المتوسطية، المُعدّة بخبرة من أجود المكوّنات.'),
(@Home, N'menu_item_1_label', 'Text', @en, N'Menu Item 1'),
(@Home, N'menu_item_1_label', 'Text', @ar, N'صنف 1'),
(@Home, N'menu_item_2_label', 'Text', @en, N'Menu Item 2'),
(@Home, N'menu_item_2_label', 'Text', @ar, N'صنف 2'),
(@Home, N'menu_item_3_label', 'Text', @en, N'Menu Item 3'),
(@Home, N'menu_item_3_label', 'Text', @ar, N'صنف 3'),
(@Home, N'menu_cta_label', 'Text', @en, N'View Full Menu'),
(@Home, N'menu_cta_label', 'Text', @ar, N'شاهد قائمة الطعام الكاملة'),
(@Home, N'spaces_title', 'Text', @en, N'Our Spaces'),
(@Home, N'spaces_title', 'Text', @ar, N'أجواؤنا'),
(@Home, N'spaces_subtitle', 'Text', @en, N'Explore our diverse venues designed for every occasion and experience.'),
(@Home, N'spaces_subtitle', 'Text', @ar, N'اكتشف أجواءنا المتنوعة المصممة لكل مناسبة وتجربة.'),
(@Home, N'spaces_card_1_title', 'Text', @en, N'Dining & Shisha'),
(@Home, N'spaces_card_1_title', 'Text', @ar, N'الطعام والأرجيلة'),
(@Home, N'spaces_card_1_body', 'Text', @en, N'Elegant dining spaces with authentic Lebanese hospitality.'),
(@Home, N'spaces_card_1_body', 'Text', @ar, N'أجواء طعام أنيقة تجمع بين الضيافة اللبنانية الأصيلة.'),
(@Home, N'spaces_card_2_title', 'Text', @en, N'Indoor & Outdoor Spaces'),
(@Home, N'spaces_card_2_title', 'Text', @ar, N'أجواء داخلية وخارجية'),
(@Home, N'spaces_card_2_body', 'Text', @en, N'Versatile venues for any gathering, with stunning ambiance.'),
(@Home, N'spaces_card_2_body', 'Text', @ar, N'أجواء متعددة الاستخدامات تناسب كل تجمّع، بأجواء ساحرة.'),
(@Home, N'spaces_card_3_title', 'Text', @en, N'Work & Casual Meetings'),
(@Home, N'spaces_card_3_title', 'Text', @ar, N'العمل واللقاءات غير الرسمية'),
(@Home, N'spaces_card_3_body', 'Text', @en, N'Perfect environment for productive meetings and informal gatherings.'),
(@Home, N'spaces_card_3_body', 'Text', @ar, N'بيئة مثالية للاجتماعات المثمرة واللقاءات غير الرسمية.'),
(@Home, N'events_title', 'Text', @en, N'Events at Misk'),
(@Home, N'events_title', 'Text', @ar, N'المناسبات في مسك'),
(@Home, N'events_card_1_title', 'Text', @en, N'Football & Live Match Screenings'),
(@Home, N'events_card_1_title', 'Text', @ar, N'كرة القدم وعرض المباريات المباشرة'),
(@Home, N'events_card_1_body', 'Text', @en, N'Experience the thrill of live sports in our premium viewing spaces with world-class amenities.'),
(@Home, N'events_card_1_body', 'Text', @ar, N'عِش إثارة الرياضة المباشرة في أجواء مشاهدة راقية بمرافق عالمية المستوى.'),
(@Home, N'events_card_2_title', 'Text', @en, N'Private Events & Celebrations'),
(@Home, N'events_card_2_title', 'Text', @ar, N'المناسبات الخاصة والاحتفالات'),
(@Home, N'events_card_2_body', 'Text', @en, N'Create unforgettable moments with our bespoke event planning and luxurious venue spaces.'),
(@Home, N'events_card_2_body', 'Text', @ar, N'اصنع لحظات لا تُنسى مع تنظيم مناسبات مخصص وأجواء فاخرة.'),
(@Home, N'gallery_title', 'Text', @en, N'Follow Our Journey'),
(@Home, N'gallery_title', 'Text', @ar, N'تابع رحلتنا'),
(@Home, N'gallery_subtitle', 'Text', @en, N'Discover moments from Misk Beirut on our social media channels.'),
(@Home, N'gallery_subtitle', 'Text', @ar, N'اكتشف لحظات من مسك بيروت عبر منصاتنا على وسائل التواصل الاجتماعي.'),
(@Home, N'gallery_photo_1_caption', 'Text', @en, N'Photo 1'),
(@Home, N'gallery_photo_1_caption', 'Text', @ar, N'صورة 1'),
(@Home, N'gallery_photo_2_caption', 'Text', @en, N'Photo 2'),
(@Home, N'gallery_photo_2_caption', 'Text', @ar, N'صورة 2'),
(@Home, N'gallery_photo_3_caption', 'Text', @en, N'Photo 3'),
(@Home, N'gallery_photo_3_caption', 'Text', @ar, N'صورة 3'),
(@Home, N'gallery_photo_4_caption', 'Text', @en, N'Photo 4'),
(@Home, N'gallery_photo_4_caption', 'Text', @ar, N'صورة 4'),
(@Home, N'gallery_photo_5_caption', 'Text', @en, N'Photo 5'),
(@Home, N'gallery_photo_5_caption', 'Text', @ar, N'صورة 5'),
(@Home, N'gallery_photo_6_caption', 'Text', @en, N'Photo 6'),
(@Home, N'gallery_photo_6_caption', 'Text', @ar, N'صورة 6'),
(@Home, N'gallery_photo_7_caption', 'Text', @en, N'Photo 7'),
(@Home, N'gallery_photo_7_caption', 'Text', @ar, N'صورة 7'),
(@Home, N'gallery_photo_8_caption', 'Text', @en, N'Photo 8'),
(@Home, N'gallery_photo_8_caption', 'Text', @ar, N'صورة 8'),
(@Home, N'gallery_instagram_label', 'Text', @en, N'Follow @MiskBeirut on Instagram'),
(@Home, N'gallery_instagram_label', 'Text', @ar, N'تابعونا على إنستغرام MiskBeirut@'),
(@Home, N'gallery_instagram_url', 'Link', @en, N'#'),
(@Home, N'gallery_instagram_url', 'Link', @ar, N'#'),
(@Home, N'testimonials_title', 'Text', @en, N'What Our Guests Say'),
(@Home, N'testimonials_title', 'Text', @ar, N'ماذا يقول ضيوفنا'),
(@Home, N'testimonial_1_quote', 'Text', @en, N'The best mezze I''ve ever had outside of my grandmother''s kitchen. The ambiance is truly world-class.'),
(@Home, N'testimonial_1_quote', 'Text', @ar, N'أفضل مازة تذوقتها خارج مطبخ جدتي. الأجواء عالمية المستوى بحق.'),
(@Home, N'testimonial_1_author', 'Text', @en, N'Sofia Rossi'),
(@Home, N'testimonial_1_author', 'Text', @ar, N'Sofia Rossi'),
(@Home, N'testimonial_1_location', 'Text', @en, N'Milan, Italy'),
(@Home, N'testimonial_1_location', 'Text', @ar, N'ميلانو، إيطاليا'),
(@Home, N'testimonial_2_quote', 'Text', @en, N'Editorial-level presentation with flavors that stay true to their roots. A masterpiece of modern dining.'),
(@Home, N'testimonial_2_quote', 'Text', @ar, N'تقديم يضاهي المجلات الفاخرة، مع نكهات أصيلة لم تفقد جذورها. تحفة من تحف الطعام العصري.'),
(@Home, N'testimonial_2_author', 'Text', @en, N'Julian Vane'),
(@Home, N'testimonial_2_author', 'Text', @ar, N'Julian Vane'),
(@Home, N'testimonial_2_location', 'Text', @en, N'Food Critic'),
(@Home, N'testimonial_2_location', 'Text', @ar, N'ناقد طعام'),
(@Home, N'testimonial_3_quote', 'Text', @en, N'The hospitality here is unparalleled. It''s not just a meal; it''s a feeling of coming home.'),
(@Home, N'testimonial_3_quote', 'Text', @ar, N'الضيافة هنا لا مثيل لها. إنها ليست مجرد وجبة، بل شعور بالعودة إلى الوطن.'),
(@Home, N'testimonial_3_author', 'Text', @en, N'Amina Al-Farsi'),
(@Home, N'testimonial_3_author', 'Text', @ar, N'أمينة الفارسي'),
(@Home, N'testimonial_3_location', 'Text', @en, N'Dubai, UAE'),
(@Home, N'testimonial_3_location', 'Text', @ar, N'دبي، الإمارات'),
(@Home, N'visit_title', 'Text', @en, N'Visit Misk Beirut'),
(@Home, N'visit_title', 'Text', @ar, N'زوروا مسك بيروت'),
(@Home, N'visit_address', 'Text', @en, N'123 Rue de Gourmet, Beirut'),
(@Home, N'visit_address', 'Text', @ar, N'123 شارع غورميه، بيروت'),
(@Home, N'visit_address_map_url', 'Link', @en, N'https://www.google.com/maps/search/123+Rue+de+Gourmet,+Beirut,+Lebanon'),
(@Home, N'visit_address_map_url', 'Link', @ar, N'https://www.google.com/maps/search/123+Rue+de+Gourmet,+Beirut,+Lebanon'),
(@Home, N'visit_hours', 'Text', @en, N'12:00 PM - 12:00 AM'),
(@Home, N'visit_hours', 'Text', @ar, N'12:00 ظهراً - 12:00 منتصف الليل'),
(@Home, N'visit_phone', 'Text', @en, N'+961 1 234 567'),
(@Home, N'visit_phone', 'Text', @ar, N'+961 1 234 567'),
(@Home, N'visit_phone_link', 'Text', @en, N'+9611234567'),
(@Home, N'visit_phone_link', 'Text', @ar, N'+9611234567'),
(@Home, N'visit_email', 'Text', @en, N'concierge@miskbeirut.com'),
(@Home, N'visit_email', 'Text', @ar, N'concierge@miskbeirut.com'),
(@Home, N'visit_cta_label', 'Text', @en, N'Reserve a Table'),
(@Home, N'visit_cta_label', 'Text', @ar, N'احجز طاولة'),
(@Home, N'visit_map_embed_url', 'Link', @en, N'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3311.834712345678!2d35.5017!3d33.8938!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x151f17215880a787%3A0x49621703add375d!2sBeirut%2C%20Lebanon!5e0!3m2!1sen!2slb!4v1710000000000!5m2!1sen!2slb'),
(@Home, N'visit_map_embed_url', 'Link', @ar, N'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3311.834712345678!2d35.5017!3d33.8938!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x151f17215880a787%3A0x49621703add375d!2sBeirut%2C%20Lebanon!5e0!3m2!1sen!2slb!4v1710000000000!5m2!1sen!2slb'),
(@Home, N'careers_banner_title', 'Text', @en, N'Join Our Team'),
(@Home, N'careers_banner_title', 'Text', @ar, N'انضم إلى فريقنا'),
(@Home, N'careers_banner_body', 'Text', @en, N'Build your career with us and become part of Misk Beirut''s legacy of excellence.'),
(@Home, N'careers_banner_body', 'Text', @ar, N'ابنِ مسيرتك المهنية معنا وكن جزءاً من إرث مسك بيروت في التميز.'),
(@Home, N'careers_banner_cta_label', 'Text', @en, N'View Careers'),
(@Home, N'careers_banner_cta_label', 'Text', @ar, N'شاهد الوظائف');

-- 5) About -----------------------------------------------------------------------------------
INSERT INTO customer.page_attributes (PageId, AttributeName, AttributeType, LangId, Value) VALUES
(@About, N'hero_title', 'Text', @en, N'About Misk Beirut'),
(@About, N'hero_title', 'Text', @ar, N'عن مسك بيروت'),
(@About, N'hero_subtitle', 'Text', @en, N'A timeless sanctuary of Levantine hospitality, where every dish tells a story of heritage and every visit feels like coming home.'),
(@About, N'hero_subtitle', 'Text', @ar, N'ملاذ خالد للضيافة الشامية، حيث يروي كل طبق حكاية تراث، وتشعر في كل زيارة أنك عائد إلى الوطن.'),
(@About, N'hero_image', 'Image', @en, N'https://lh3.googleusercontent.com/aida-public/AB6AXuCrG1HU9jiVr-8Wn2Fm5iex47uAo0h1sHnHlW_uqvIOaesHotr02DT6PDsoSpz2QYySz1W_5Y6jl6ewWoMQGKjhrC0KxodVzbgdRAwS4w8h3FBNDuqvoYfON-hBiR7JuweJvXd8JZ98ruQbemyumsiTQZCwCUFCnoRUU_8oyGSn-yuWU62PZIcVclnmhAmZzexpp81ykRoz5QedPmzUaFaB7xwqdhH_8-iEaeCubM-5UY4gdjQD367JMPITI75ljnUHeXwoqPiil8I'),
(@About, N'hero_image', 'Image', @ar, N'https://lh3.googleusercontent.com/aida-public/AB6AXuCrG1HU9jiVr-8Wn2Fm5iex47uAo0h1sHnHlW_uqvIOaesHotr02DT6PDsoSpz2QYySz1W_5Y6jl6ewWoMQGKjhrC0KxodVzbgdRAwS4w8h3FBNDuqvoYfON-hBiR7JuweJvXd8JZ98ruQbemyumsiTQZCwCUFCnoRUU_8oyGSn-yuWU62PZIcVclnmhAmZzexpp81ykRoz5QedPmzUaFaB7xwqdhH_8-iEaeCubM-5UY4gdjQD367JMPITI75ljnUHeXwoqPiil8I'),
(@About, N'founder_eyebrow', 'Text', @en, N'Since 1982'),
(@About, N'founder_eyebrow', 'Text', @ar, N'منذ عام 1982'),
(@About, N'founder_title', 'Text', @en, N'Our Story'),
(@About, N'founder_title', 'Text', @ar, N'قصتنا'),
(@About, N'founder_name', 'Text', @en, N'Elias Mansour'),
(@About, N'founder_name', 'Text', @ar, N'إلياس منصور'),
(@About, N'founder_role', 'Text', @en, N'Founder & Visionary'),
(@About, N'founder_role', 'Text', @ar, N'المؤسس وصاحب الرؤية'),
(@About, N'founder_image', 'Image', @en, N'https://lh3.googleusercontent.com/aida-public/AB6AXuA2y7a7-zElnk20Xu4CUOsjUdqyUXYehOnwqWx7ei1y4VcdtdXC6YwHbhMgG9BDcLzLxs1Zo1H80TxcmJtpS3GCE2xDe7QZQ-vwY-DCIDSEgGgxz75B2IXO0xx8PBTMDIwsrhbK6Aws7m2_Z0xJlOXPPgZP36FsINRKypve8QfUFVEgbeX6ephE1zZSJ6alXgkmuh9Kj2AfsGqHhIfBt8pUJN1SnJ6NE53EbR64Pruapj2FaCFMV5MDVe47Mit9dzNy-buhhS9_dz0'),
(@About, N'founder_image', 'Image', @ar, N'https://lh3.googleusercontent.com/aida-public/AB6AXuA2y7a7-zElnk20Xu4CUOsjUdqyUXYehOnwqWx7ei1y4VcdtdXC6YwHbhMgG9BDcLzLxs1Zo1H80TxcmJtpS3GCE2xDe7QZQ-vwY-DCIDSEgGgxz75B2IXO0xx8PBTMDIwsrhbK6Aws7m2_Z0xJlOXPPgZP36FsINRKypve8QfUFVEgbeX6ephE1zZSJ6alXgkmuh9Kj2AfsGqHhIfBt8pUJN1SnJ6NE53EbR64Pruapj2FaCFMV5MDVe47Mit9dzNy-buhhS9_dz0'),
(@About, N'founder_body_1', 'RichText', @en, N'Misk Beirut began as a modest kitchen in the heart of pre-war Beirut, driven by Elias Mansour''s unwavering belief that the soul of Lebanese culture resides in its flavors. What started as a small gathering place for poets and painters blossomed into a sanctuary for authentic Levantine gastronomy.'),
(@About, N'founder_body_1', 'RichText', @ar, N'بدأ مسك بيروت كمطبخ متواضع في قلب بيروت ما قبل الحرب، إيماناً راسخاً من إلياس منصور بأن روح الثقافة اللبنانية تكمن في نكهاتها. وما بدأ كملتقى صغير للشعراء والرسامين، تحوّل إلى ملاذ لفن الطهي الشامي الأصيل.'),
(@About, N'founder_body_2', 'RichText', @en, N'Over four decades, we have remained anchored in our commitment to artisanal Levant techniques—sourcing the finest sumac from the mountains, olive oil from the groves of Koura, and hospitality from the depths of our heritage.'),
(@About, N'founder_body_2', 'RichText', @ar, N'على مدى أربعة عقود، ظللنا ملتزمين بأساليب الطهي الشامية التقليدية؛ من أجود أنواع السماق من الجبال، وزيت الزيتون من بساتين الكورة، إلى ضيافة نابعة من أعماق تراثنا.'),
(@About, N'founder_quote', 'Text', @en, N'"An honest approach to food, focusing on the integrity of ingredients and the warmth of Lebanese tradition."'),
(@About, N'founder_quote', 'Text', @ar, N'"نهجٌ صادق تجاه الطعام، يركّز على نقاء المكوّنات ودفء التقاليد اللبنانية."'),
(@About, N'values_title', 'Text', @en, N'The Pillars of Misk'),
(@About, N'values_title', 'Text', @ar, N'ركائز مسك'),
(@About, N'value_1_title', 'Text', @en, N'Heritage'),
(@About, N'value_1_title', 'Text', @ar, N'التراث'),
(@About, N'value_1_body', 'Text', @en, N'Preserving the generational secrets of Lebanese culinary arts while embracing contemporary refinement.'),
(@About, N'value_1_body', 'Text', @ar, N'الحفاظ على أسرار فن الطهي اللبناني المتوارثة، مع تبنّي الرقي المعاصر.'),
(@About, N'value_2_title', 'Text', @en, N'Quality'),
(@About, N'value_2_title', 'Text', @ar, N'الجودة'),
(@About, N'value_2_body', 'Text', @en, N'Sourcing without compromise. Every ingredient is selected for its purity, origin, and seasonal peak.'),
(@About, N'value_2_body', 'Text', @ar, N'لا مساومة في اختيار المكوّنات؛ كل عنصر يُنتقى لنقائه ومصدره وموسمه الأمثل.'),
(@About, N'value_3_title', 'Text', @en, N'Community'),
(@About, N'value_3_title', 'Text', @ar, N'المجتمع'),
(@About, N'value_3_body', 'Text', @en, N'Creating a table where every guest is family. Our hospitality extends far beyond the dining room.'),
(@About, N'value_3_body', 'Text', @ar, N'نصنع مائدة يكون فيها كل ضيف كأنه من العائلة. ضيافتنا تتجاوز حدود صالة الطعام.'),
(@About, N'timeline_title', 'Text', @en, N'Our Journey Through Time'),
(@About, N'timeline_title', 'Text', @ar, N'رحلتنا عبر الزمن'),
(@About, N'timeline_1_year', 'Text', @en, N'1982'),
(@About, N'timeline_1_year', 'Text', @ar, N'1982'),
(@About, N'timeline_1_title', 'Text', @en, N'The Founding'),
(@About, N'timeline_1_title', 'Text', @ar, N'التأسيس'),
(@About, N'timeline_1_body', 'Text', @en, N'Elias Mansour opens the first Misk oven in Beirut, focused on artisanal manousheh and traditional mezze.'),
(@About, N'timeline_1_body', 'Text', @ar, N'افتتح إلياس منصور أول فرن مسك في بيروت، متخصصاً في المناقيش الحرفية والمازة التقليدية.'),
(@About, N'timeline_1_image', 'Image', @en, N'https://lh3.googleusercontent.com/aida-public/AB6AXuCCdF6LEY22Ddw6q2vZg0lDg2V4zik2-XFh2jDO-e1O-59q-2YCEhy-v8f8vZ1Omofg_ZWGnjsLwa123CsEsk1Ph9l7-H0Mcl_hycSRn5Ty4ARuTMylkzV0L6W-D-z45T_SnERDINs18P6dBEt6pbBx7FX9meHBeYkAqJn1VuIcztrk4gA7nMYSFdAbmVTNq4czenSkN4cWsQJg7rvOjqvfpCcIroep_CpG7CZP8LMwSVqde0JR0F3Zknifm74-YFnl8N3_aZcq6_c'),
(@About, N'timeline_1_image', 'Image', @ar, N'https://lh3.googleusercontent.com/aida-public/AB6AXuCCdF6LEY22Ddw6q2vZg0lDg2V4zik2-XFh2jDO-e1O-59q-2YCEhy-v8f8vZ1Omofg_ZWGnjsLwa123CsEsk1Ph9l7-H0Mcl_hycSRn5Ty4ARuTMylkzV0L6W-D-z45T_SnERDINs18P6dBEt6pbBx7FX9meHBeYkAqJn1VuIcztrk4gA7nMYSFdAbmVTNq4czenSkN4cWsQJg7rvOjqvfpCcIroep_CpG7CZP8LMwSVqde0JR0F3Zknifm74-YFnl8N3_aZcq6_c'),
(@About, N'timeline_2_year', 'Text', @en, N'2004'),
(@About, N'timeline_2_year', 'Text', @ar, N'2004'),
(@About, N'timeline_2_title', 'Text', @en, N'Expansion'),
(@About, N'timeline_2_title', 'Text', @ar, N'التوسع'),
(@About, N'timeline_2_body', 'Text', @en, N'Relocation to a historic manor in the Central District, transforming into a full-scale culinary destination.'),
(@About, N'timeline_2_body', 'Text', @ar, N'الانتقال إلى قصر تاريخي في وسط البلد، ليتحول إلى وجهة طهي متكاملة.'),
(@About, N'timeline_2_image', 'Image', @en, N'https://lh3.googleusercontent.com/aida-public/AB6AXuDdGG6jGIU1UZ_A7e7h6wLUr1fsaH56V9cITtL_b0KOxiD1ajBB-IJgi92YIh1kkia1mpNNKD841B-SjoNF6888vQA4P0XlOE4B7anbEsAYDdNG--ifAK8-X2h2ph9y51-RpksVBJkefd3GpWzp37zzeENXVH2E3EJf2eTtw5dWlaN271s5xK8nighbmq8AisL1PRr77xCO6jgVHMJFJ5heHaN4eHVS5xcRmwiVftmR03zIPXlZN5SQtpclgtSB3Nr5XR6Rayu8nMQ'),
(@About, N'timeline_2_image', 'Image', @ar, N'https://lh3.googleusercontent.com/aida-public/AB6AXuDdGG6jGIU1UZ_A7e7h6wLUr1fsaH56V9cITtL_b0KOxiD1ajBB-IJgi92YIh1kkia1mpNNKD841B-SjoNF6888vQA4P0XlOE4B7anbEsAYDdNG--ifAK8-X2h2ph9y51-RpksVBJkefd3GpWzp37zzeENXVH2E3EJf2eTtw5dWlaN271s5xK8nighbmq8AisL1PRr77xCO6jgVHMJFJ5heHaN4eHVS5xcRmwiVftmR03zIPXlZN5SQtpclgtSB3Nr5XR6Rayu8nMQ'),
(@About, N'timeline_3_year', 'Text', @en, N'Today'),
(@About, N'timeline_3_year', 'Text', @ar, N'اليوم'),
(@About, N'timeline_3_title', 'Text', @en, N'Contemporary Sanctuary'),
(@About, N'timeline_3_title', 'Text', @ar, N'ملاذ معاصر'),
(@About, N'timeline_3_body', 'Text', @en, N'Now a multi-award winning institution, bridging traditional Levantine warmth with modern luxury across the globe.'),
(@About, N'timeline_3_body', 'Text', @ar, N'اليوم، أصبح مؤسسة حائزة على جوائز عديدة، تجمع بين دفء الضيافة الشامية التقليدية والفخامة العصرية حول العالم.'),
(@About, N'timeline_3_image', 'Image', @en, N'https://lh3.googleusercontent.com/aida-public/AB6AXuC2L5NgH4nGpGkzbLByRfzw9pbhHOYkY16GWKCXNN4U7tORFVysXUyjnpnivnvX7H_g1QozXbL5tEjNlGS3C9VcoegIo_nvlok3biGhhjZNqYDqYLpcmhYcdXoCMXtj2RtDZpIHoaYNmS4QGiHIbclMxiFFi5jnvhEeCbhL-imJ0gBPyojEgJgQ8qv9Tkq4VvMJ6QtWjZvhJP5lX3ALysr9tsqvzb2HaFW3zI8Ab3bGPXKlG8oJpcMh4hMnrI53k3GgUhbHL83IPsQ'),
(@About, N'timeline_3_image', 'Image', @ar, N'https://lh3.googleusercontent.com/aida-public/AB6AXuC2L5NgH4nGpGkzbLByRfzw9pbhHOYkY16GWKCXNN4U7tORFVysXUyjnpnivnvX7H_g1QozXbL5tEjNlGS3C9VcoegIo_nvlok3biGhhjZNqYDqYLpcmhYcdXoCMXtj2RtDZpIHoaYNmS4QGiHIbclMxiFFi5jnvhEeCbhL-imJ0gBPyojEgJgQ8qv9Tkq4VvMJ6QtWjZvhJP5lX3ALysr9tsqvzb2HaFW3zI8Ab3bGPXKlG8oJpcMh4hMnrI53k3GgUhbHL83IPsQ');

-- 6) Careers ---------------------------------------------------------------------------------
INSERT INTO customer.page_attributes (PageId, AttributeName, AttributeType, LangId, Value) VALUES
(@Careers, N'hero_title', 'Text', @en, N'Careers at Misk Beirut'),
(@Careers, N'hero_title', 'Text', @ar, N'الوظائف في مسك بيروت'),
(@Careers, N'hero_subtitle', 'Text', @en, N'Join a team dedicated to redefining Mediterranean hospitality. We seek visionaries, artisans, and professionals who share our passion for excellence and Levantine culture.'),
(@Careers, N'hero_subtitle', 'Text', @ar, N'انضم إلى فريق يسعى لإعادة تعريف الضيافة المتوسطية. نبحث عن أصحاب رؤية وحرفيين ومحترفين يشاركوننا شغفنا بالتميز والثقافة الشامية.'),
(@Careers, N'hero_image', 'Image', @en, N'https://lh3.googleusercontent.com/aida-public/AB6AXuCrG1HU9jiVr-8Wn2Fm5iex47uAo0h1sHnHlW_uqvIOaesHotr02DT6PDsoSpz2QYySz1W_5Y6jl6ewWoMQGKjhrC0KxodVzbgdRAwS4w8h3FBNDuqvoYfON-hBiR7JuweJvXd8JZ98ruQbemyumsiTQZCwCUFCnoRUU_8oyGSn-yuWU62PZIcVclnmhAmZzexpp81ykRoz5QedPmzUaFaB7xwqdhH_8-iEaeCubM-5UY4gdjQD367JMPITI75ljnUHeXwoqPiil8I'),
(@Careers, N'hero_image', 'Image', @ar, N'https://lh3.googleusercontent.com/aida-public/AB6AXuCrG1HU9jiVr-8Wn2Fm5iex47uAo0h1sHnHlW_uqvIOaesHotr02DT6PDsoSpz2QYySz1W_5Y6jl6ewWoMQGKjhrC0KxodVzbgdRAwS4w8h3FBNDuqvoYfON-hBiR7JuweJvXd8JZ98ruQbemyumsiTQZCwCUFCnoRUU_8oyGSn-yuWU62PZIcVclnmhAmZzexpp81ykRoz5QedPmzUaFaB7xwqdhH_8-iEaeCubM-5UY4gdjQD367JMPITI75ljnUHeXwoqPiil8I'),
(@Careers, N'value_strip_1_label', 'Text', @en, N'Career Growth'),
(@Careers, N'value_strip_1_label', 'Text', @ar, N'نمو مهني'),
(@Careers, N'value_strip_2_label', 'Text', @en, N'Diverse Culture'),
(@Careers, N'value_strip_2_label', 'Text', @ar, N'ثقافة متنوعة'),
(@Careers, N'value_strip_3_label', 'Text', @en, N'Competitive Benefits'),
(@Careers, N'value_strip_3_label', 'Text', @ar, N'مزايا تنافسية'),
(@Careers, N'value_strip_4_label', 'Text', @en, N'Culinary Excellence'),
(@Careers, N'value_strip_4_label', 'Text', @ar, N'تميز في فن الطهي'),
(@Careers, N'vacancies_title', 'Text', @en, N'Open Positions'),
(@Careers, N'vacancies_title', 'Text', @ar, N'الوظائف الشاغرة'),
(@Careers, N'vacancy_1_title', 'Text', @en, N'Head Chef'),
(@Careers, N'vacancy_1_title', 'Text', @ar, N'الشيف التنفيذي'),
(@Careers, N'vacancy_1_department', 'Text', @en, N'Culinary'),
(@Careers, N'vacancy_1_department', 'Text', @ar, N'المطبخ'),
(@Careers, N'vacancy_1_location', 'Text', @en, N'Beirut'),
(@Careers, N'vacancy_1_location', 'Text', @ar, N'بيروت'),
(@Careers, N'vacancy_1_type', 'Text', @en, N'Full-Time'),
(@Careers, N'vacancy_1_type', 'Text', @ar, N'دوام كامل'),
(@Careers, N'vacancy_2_title', 'Text', @en, N'F&B Consultant'),
(@Careers, N'vacancy_2_title', 'Text', @ar, N'مستشار أغذية ومشروبات'),
(@Careers, N'vacancy_2_department', 'Text', @en, N'Consulting'),
(@Careers, N'vacancy_2_department', 'Text', @ar, N'استشارات'),
(@Careers, N'vacancy_2_location', 'Text', @en, N'Remote'),
(@Careers, N'vacancy_2_location', 'Text', @ar, N'عن بُعد'),
(@Careers, N'vacancy_2_type', 'Text', @en, N'Full-Time'),
(@Careers, N'vacancy_2_type', 'Text', @ar, N'دوام كامل'),
(@Careers, N'vacancy_3_title', 'Text', @en, N'Events Coordinator'),
(@Careers, N'vacancy_3_title', 'Text', @ar, N'منسق مناسبات'),
(@Careers, N'vacancy_3_department', 'Text', @en, N'Events'),
(@Careers, N'vacancy_3_department', 'Text', @ar, N'المناسبات'),
(@Careers, N'vacancy_3_location', 'Text', @en, N'Beirut'),
(@Careers, N'vacancy_3_location', 'Text', @ar, N'بيروت'),
(@Careers, N'vacancy_3_type', 'Text', @en, N'Full-Time'),
(@Careers, N'vacancy_3_type', 'Text', @ar, N'دوام كامل'),
(@Careers, N'vacancy_4_title', 'Text', @en, N'Restaurant Manager'),
(@Careers, N'vacancy_4_title', 'Text', @ar, N'مدير المطعم'),
(@Careers, N'vacancy_4_department', 'Text', @en, N'Operations'),
(@Careers, N'vacancy_4_department', 'Text', @ar, N'العمليات'),
(@Careers, N'vacancy_4_location', 'Text', @en, N'Beirut'),
(@Careers, N'vacancy_4_location', 'Text', @ar, N'بيروت'),
(@Careers, N'vacancy_4_type', 'Text', @en, N'Full-Time'),
(@Careers, N'vacancy_4_type', 'Text', @ar, N'دوام كامل'),
(@Careers, N'apply_now_label', 'Text', @en, N'Apply Now'),
(@Careers, N'apply_now_label', 'Text', @ar, N'تقدم الآن'),
(@Careers, N'apply_prefix_label', 'Text', @en, N'Application for'),
(@Careers, N'apply_prefix_label', 'Text', @ar, N'طلب توظيف لوظيفة'),
(@Careers, N'submit_label', 'Text', @en, N'Submit Application'),
(@Careers, N'submit_label', 'Text', @ar, N'إرسال الطلب'),
(@Careers, N'form_field_full_name', 'Text', @en, N'Full Name'),
(@Careers, N'form_field_full_name', 'Text', @ar, N'الاسم الكامل'),
(@Careers, N'form_field_phone', 'Text', @en, N'Phone Number'),
(@Careers, N'form_field_phone', 'Text', @ar, N'رقم الهاتف'),
(@Careers, N'form_field_email', 'Text', @en, N'Email Address'),
(@Careers, N'form_field_email', 'Text', @ar, N'البريد الإلكتروني'),
(@Careers, N'form_field_cover_message', 'Text', @en, N'Cover Message'),
(@Careers, N'form_field_cover_message', 'Text', @ar, N'رسالة تعريفية'),
(@Careers, N'form_field_upload_cv', 'Text', @en, N'Upload CV (PDF)'),
(@Careers, N'form_field_upload_cv', 'Text', @ar, N'تحميل السيرة الذاتية (PDF)'),
(@Careers, N'form_placeholder_name', 'Text', @en, N'YOUR NAME'),
(@Careers, N'form_placeholder_name', 'Text', @ar, N'اسمك'),
(@Careers, N'form_placeholder_phone', 'Text', @en, N'+961 00 000 000'),
(@Careers, N'form_placeholder_phone', 'Text', @ar, N'+961 00 000 000'),
(@Careers, N'form_placeholder_email', 'Text', @en, N'EMAIL@EXAMPLE.COM'),
(@Careers, N'form_placeholder_email', 'Text', @ar, N'EMAIL@EXAMPLE.COM'),
(@Careers, N'form_placeholder_cover', 'Text', @en, N'TELL US ABOUT YOUR EXPERIENCE'),
(@Careers, N'form_placeholder_cover', 'Text', @ar, N'أخبرنا عن خبرتك'),
(@Careers, N'culture_title', 'Text', @en, N'Our Culture'),
(@Careers, N'culture_title', 'Text', @ar, N'ثقافتنا'),
(@Careers, N'culture_body', 'Text', @en, N'At Misk Beirut, we believe the best experiences are built by those who value hospitality as an art form. We provide a space where talent is nurtured and culinary dreams are realized.'),
(@Careers, N'culture_body', 'Text', @ar, N'في مسك بيروت، نؤمن بأن أفضل التجارب يصنعها من يرى في الضيافة فناً قائماً بذاته. نوفر بيئة تُصقل فيها المواهب وتتحقق فيها أحلام الطهي.'),
(@Careers, N'culture_image', 'Image', @en, N'https://lh3.googleusercontent.com/aida-public/AB6AXuBm3jJoNgH5s_rjzKLIalc1OKH9G55ORI52lhD7OeGph-n2gcT5dekQLAYWRpwCa12EvucvrjYgo0cCAG4lDJlj96TyCKzg8f1jJQZQ3VlcJa6BHfZ5cU85A4Z6drunWobaEUcuTeigHzlJKfNOwoW1JK5Th93ZwxpQU9N_SGCu9992NM3FTarqoG2q5zLSNpDJ3MPGjG_8XcUdxCpAFMUPJy0lgcKypJMN5tDH2ca6Av5415pdZeIZGYMYl7u9kVHG2ppuQ0DY5vI'),
(@Careers, N'culture_image', 'Image', @ar, N'https://lh3.googleusercontent.com/aida-public/AB6AXuBm3jJoNgH5s_rjzKLIalc1OKH9G55ORI52lhD7OeGph-n2gcT5dekQLAYWRpwCa12EvucvrjYgo0cCAG4lDJlj96TyCKzg8f1jJQZQ3VlcJa6BHfZ5cU85A4Z6drunWobaEUcuTeigHzlJKfNOwoW1JK5Th93ZwxpQU9N_SGCu9992NM3FTarqoG2q5zLSNpDJ3MPGjG_8XcUdxCpAFMUPJy0lgcKypJMN5tDH2ca6Av5415pdZeIZGYMYl7u9kVHG2ppuQ0DY5vI');

-- 7) Contact ---------------------------------------------------------------------------------
INSERT INTO customer.page_attributes (PageId, AttributeName, AttributeType, LangId, Value) VALUES
(@Contact, N'hero_title', 'Text', @en, N'Get In Touch'),
(@Contact, N'hero_title', 'Text', @ar, N'تواصل معنا'),
(@Contact, N'hero_subtitle', 'Text', @en, N'Whether you are seeking a culinary escape, professional consultation, or have a general inquiry, our doors are always open.'),
(@Contact, N'hero_subtitle', 'Text', @ar, N'سواء كنت تبحث عن تجربة طهي مميزة، أو استشارة مهنية، أو لديك استفسار عام، أبوابنا مفتوحة دائماً.'),
(@Contact, N'hero_image', 'Image', @en, N'https://lh3.googleusercontent.com/aida-public/AB6AXuCrG1HU9jiVr-8Wn2Fm5iex47uAo0h1sHnHlW_uqvIOaesHotr02DT6PDsoSpz2QYySz1W_5Y6jl6ewWoMQGKjhrC0KxodVzbgdRAwS4w8h3FBNDuqvoYfON-hBiR7JuweJvXd8JZ98ruQbemyumsiTQZCwCUFCnoRUU_8oyGSn-yuWU62PZIcVclnmhAmZzexpp81ykRoz5QedPmzUaFaB7xwqdhH_8-iEaeCubM-5UY4gdjQD367JMPITI75ljnUHeXwoqPiil8I'),
(@Contact, N'hero_image', 'Image', @ar, N'https://lh3.googleusercontent.com/aida-public/AB6AXuCrG1HU9jiVr-8Wn2Fm5iex47uAo0h1sHnHlW_uqvIOaesHotr02DT6PDsoSpz2QYySz1W_5Y6jl6ewWoMQGKjhrC0KxodVzbgdRAwS4w8h3FBNDuqvoYfON-hBiR7JuweJvXd8JZ98ruQbemyumsiTQZCwCUFCnoRUU_8oyGSn-yuWU62PZIcVclnmhAmZzexpp81ykRoz5QedPmzUaFaB7xwqdhH_8-iEaeCubM-5UY4gdjQD367JMPITI75ljnUHeXwoqPiil8I'),
(@Contact, N'info_call_title', 'Text', @en, N'Call Us'),
(@Contact, N'info_call_title', 'Text', @ar, N'اتصل بنا'),
(@Contact, N'info_call_phone_1', 'Text', @en, N'+961 1 123 456'),
(@Contact, N'info_call_phone_1', 'Text', @ar, N'+961 1 123 456'),
(@Contact, N'info_call_phone_2', 'Text', @en, N'+961 3 987 654'),
(@Contact, N'info_call_phone_2', 'Text', @ar, N'+961 3 987 654'),
(@Contact, N'info_call_tel_link', 'Text', @en, N'+9611123456'),
(@Contact, N'info_call_tel_link', 'Text', @ar, N'+9611123456'),
(@Contact, N'info_email_title', 'Text', @en, N'Email'),
(@Contact, N'info_email_title', 'Text', @ar, N'البريد الإلكتروني'),
(@Contact, N'info_email_value', 'Text', @en, N'hello@miskbeirut.com'),
(@Contact, N'info_email_value', 'Text', @ar, N'hello@miskbeirut.com'),
(@Contact, N'info_address_title', 'Text', @en, N'Address'),
(@Contact, N'info_address_title', 'Text', @ar, N'العنوان'),
(@Contact, N'info_address_value', 'Text', @en, N'Gemmayzeh, Pasteur Street, Beirut'),
(@Contact, N'info_address_value', 'Text', @ar, N'الجميزة، شارع باستور، بيروت'),
(@Contact, N'info_address_map_url', 'Link', @en, N'https://www.google.com/maps/search/Gemmayzeh,+Pasteur+Street,+Beirut'),
(@Contact, N'info_address_map_url', 'Link', @ar, N'https://www.google.com/maps/search/Gemmayzeh,+Pasteur+Street,+Beirut'),
(@Contact, N'field_full_name', 'Text', @en, N'Full Name *'),
(@Contact, N'field_full_name', 'Text', @ar, N'الاسم الكامل *'),
(@Contact, N'field_phone', 'Text', @en, N'Phone Number *'),
(@Contact, N'field_phone', 'Text', @ar, N'رقم الهاتف *'),
(@Contact, N'field_email', 'Text', @en, N'Email Address (Optional)'),
(@Contact, N'field_email', 'Text', @ar, N'البريد الإلكتروني (اختياري)'),
(@Contact, N'field_reason', 'Text', @en, N'Reason for Contact *'),
(@Contact, N'field_reason', 'Text', @ar, N'سبب التواصل *'),
(@Contact, N'reason_placeholder', 'Text', @en, N'Select a reason...'),
(@Contact, N'reason_placeholder', 'Text', @ar, N'اختر سبباً...'),
(@Contact, N'reason_option_1', 'Text', @en, N'Consulting'),
(@Contact, N'reason_option_1', 'Text', @ar, N'استشارات'),
(@Contact, N'reason_option_2', 'Text', @en, N'Feedback'),
(@Contact, N'reason_option_2', 'Text', @ar, N'ملاحظات'),
(@Contact, N'reason_option_3', 'Text', @en, N'General Inquiry'),
(@Contact, N'reason_option_3', 'Text', @ar, N'استفسار عام'),
(@Contact, N'reason_error', 'Text', @en, N'Please select a reason for contact.'),
(@Contact, N'reason_error', 'Text', @ar, N'يرجى اختيار سبب التواصل.'),
(@Contact, N'field_message', 'Text', @en, N'Message *'),
(@Contact, N'field_message', 'Text', @ar, N'الرسالة *'),
(@Contact, N'submit_label', 'Text', @en, N'Send Inquiry'),
(@Contact, N'submit_label', 'Text', @ar, N'إرسال الطلب'),
(@Contact, N'success_message', 'Text', @en, N'Thank you for contacting us. We''ll be in touch with you soon.'),
(@Contact, N'success_message', 'Text', @ar, N'شكراً لتواصلك معنا. سنعاود الاتصال بك قريباً.'),
(@Contact, N'map_embed_url', 'Link', @en, N'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13248.847525287515!2d35.51091565!3d33.8966774!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x151f16f39369670f%3A0xc3b83c50937c050!2sBeirut%2C%20Lebanon!5e0!3m2!1sen!2sus!4v1715872145678!5m2!1sen!2sus'),
(@Contact, N'map_embed_url', 'Link', @ar, N'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13248.847525287515!2d35.51091565!3d33.8966774!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x151f16f39369670f%3A0xc3b83c50937c050!2sBeirut%2C%20Lebanon!5e0!3m2!1sen!2sus!4v1715872145678!5m2!1sen!2sus'),
(@Contact, N'fab_whatsapp_url', 'Link', @en, N'https://wa.me/9611123456'),
(@Contact, N'fab_whatsapp_url', 'Link', @ar, N'https://wa.me/9611123456');

-- 8) Events ----------------------------------------------------------------------------------
INSERT INTO customer.page_attributes (PageId, AttributeName, AttributeType, LangId, Value) VALUES
(@Events, N'hero_title', 'Text', @en, N'Events at Misk Beirut'),
(@Events, N'hero_title', 'Text', @ar, N'المناسبات في مسك بيروت'),
(@Events, N'hero_subtitle', 'Text', @en, N'Experience unforgettable moments with us'),
(@Events, N'hero_subtitle', 'Text', @ar, N'عِش لحظات لا تُنسى معنا'),
(@Events, N'hero_image', 'Image', @en, N'https://lh3.googleusercontent.com/aida-public/AB6AXuCrG1HU9jiVr-8Wn2Fm5iex47uAo0h1sHnHlW_uqvIOaesHotr02DT6PDsoSpz2QYySz1W_5Y6jl6ewWoMQGKjhrC0KxodVzbgdRAwS4w8h3FBNDuqvoYfON-hBiR7JuweJvXd8JZ98ruQbemyumsiTQZCwCUFCnoRUU_8oyGSn-yuWU62PZIcVclnmhAmZzexpp81ykRoz5QedPmzUaFaB7xwqdhH_8-iEaeCubM-5UY4gdjQD367JMPITI75ljnUHeXwoqPiil8I'),
(@Events, N'hero_image', 'Image', @ar, N'https://lh3.googleusercontent.com/aida-public/AB6AXuCrG1HU9jiVr-8Wn2Fm5iex47uAo0h1sHnHlW_uqvIOaesHotr02DT6PDsoSpz2QYySz1W_5Y6jl6ewWoMQGKjhrC0KxodVzbgdRAwS4w8h3FBNDuqvoYfON-hBiR7JuweJvXd8JZ98ruQbemyumsiTQZCwCUFCnoRUU_8oyGSn-yuWU62PZIcVclnmhAmZzexpp81ykRoz5QedPmzUaFaB7xwqdhH_8-iEaeCubM-5UY4gdjQD367JMPITI75ljnUHeXwoqPiil8I'),
(@Events, N'football_title', 'Text', @en, N'Football & Live Match Screenings'),
(@Events, N'football_title', 'Text', @ar, N'كرة القدم وعرض المباريات المباشرة'),
(@Events, N'football_body', 'Text', @en, N'Placeholder description — experience the thrill of live sports in our premium viewing spaces with world-class amenities. Final copy to be provided by the client.'),
(@Events, N'football_body', 'Text', @ar, N'نص مؤقت — عِش إثارة الرياضة المباشرة في أجواء مشاهدة راقية بمرافق عالمية المستوى. سيتم توفير النص النهائي من قبل العميل.'),
(@Events, N'football_gallery_1_caption', 'Text', @en, N'Match Day 1'),
(@Events, N'football_gallery_1_caption', 'Text', @ar, N'يوم المباراة 1'),
(@Events, N'football_gallery_2_caption', 'Text', @en, N'Match Day 2'),
(@Events, N'football_gallery_2_caption', 'Text', @ar, N'يوم المباراة 2'),
(@Events, N'football_gallery_3_caption', 'Text', @en, N'Match Day 3'),
(@Events, N'football_gallery_3_caption', 'Text', @ar, N'يوم المباراة 3'),
(@Events, N'football_gallery_4_caption', 'Text', @en, N'Match Day 4'),
(@Events, N'football_gallery_4_caption', 'Text', @ar, N'يوم المباراة 4'),
(@Events, N'football_cta_label', 'Text', @en, N'Reserve Your Spot'),
(@Events, N'football_cta_label', 'Text', @ar, N'احجز مكانك'),
(@Events, N'private_title', 'Text', @en, N'Private Events & Celebrations'),
(@Events, N'private_title', 'Text', @ar, N'المناسبات الخاصة والاحتفالات'),
(@Events, N'private_body', 'Text', @en, N'Placeholder description — create unforgettable memories with our bespoke event planning services and luxurious venues. Final copy to be provided by the client.'),
(@Events, N'private_body', 'Text', @ar, N'نص مؤقت — اصنع ذكريات لا تُنسى مع خدمات تنظيم مناسبات مخصصة وأجواء فاخرة. سيتم توفير النص النهائي من قبل العميل.'),
(@Events, N'private_gallery_1_caption', 'Text', @en, N'Weddings'),
(@Events, N'private_gallery_1_caption', 'Text', @ar, N'حفلات الزفاف'),
(@Events, N'private_gallery_2_caption', 'Text', @en, N'Corporate Events'),
(@Events, N'private_gallery_2_caption', 'Text', @ar, N'مناسبات الشركات'),
(@Events, N'private_gallery_3_caption', 'Text', @en, N'Birthday Parties'),
(@Events, N'private_gallery_3_caption', 'Text', @ar, N'حفلات أعياد الميلاد'),
(@Events, N'private_gallery_4_caption', 'Text', @en, N'Special Occasions'),
(@Events, N'private_gallery_4_caption', 'Text', @ar, N'مناسبات خاصة'),
(@Events, N'private_cta_label', 'Text', @en, N'Get in Touch'),
(@Events, N'private_cta_label', 'Text', @ar, N'تواصل معنا');

-- 9) Spaces ----------------------------------------------------------------------------------
INSERT INTO customer.page_attributes (PageId, AttributeName, AttributeType, LangId, Value) VALUES
(@Spaces, N'hero_title', 'Text', @en, N'Our Spaces'),
(@Spaces, N'hero_title', 'Text', @ar, N'أجواؤنا'),
(@Spaces, N'hero_subtitle', 'Text', @en, N'A place for every moment — from long dinners to quiet mornings'),
(@Spaces, N'hero_subtitle', 'Text', @ar, N'مكان لكل لحظة — من عشاء طويل إلى صباح هادئ'),
(@Spaces, N'hero_image', 'Image', @en, N'https://lh3.googleusercontent.com/aida-public/AB6AXuCrG1HU9jiVr-8Wn2Fm5iex47uAo0h1sHnHlW_uqvIOaesHotr02DT6PDsoSpz2QYySz1W_5Y6jl6ewWoMQGKjhrC0KxodVzbgdRAwS4w8h3FBNDuqvoYfON-hBiR7JuweJvXd8JZ98ruQbemyumsiTQZCwCUFCnoRUU_8oyGSn-yuWU62PZIcVclnmhAmZzexpp81ykRoz5QedPmzUaFaB7xwqdhH_8-iEaeCubM-5UY4gdjQD367JMPITI75ljnUHeXwoqPiil8I'),
(@Spaces, N'hero_image', 'Image', @ar, N'https://lh3.googleusercontent.com/aida-public/AB6AXuCrG1HU9jiVr-8Wn2Fm5iex47uAo0h1sHnHlW_uqvIOaesHotr02DT6PDsoSpz2QYySz1W_5Y6jl6ewWoMQGKjhrC0KxodVzbgdRAwS4w8h3FBNDuqvoYfON-hBiR7JuweJvXd8JZ98ruQbemyumsiTQZCwCUFCnoRUU_8oyGSn-yuWU62PZIcVclnmhAmZzexpp81ykRoz5QedPmzUaFaB7xwqdhH_8-iEaeCubM-5UY4gdjQD367JMPITI75ljnUHeXwoqPiil8I'),
(@Spaces, N'tab_1_label', 'Text', @en, N'Dining & Shisha'),
(@Spaces, N'tab_1_label', 'Text', @ar, N'الطعام والأرجيلة'),
(@Spaces, N'tab_2_label', 'Text', @en, N'Indoor & Outdoor Spaces'),
(@Spaces, N'tab_2_label', 'Text', @ar, N'أجواء داخلية وخارجية'),
(@Spaces, N'tab_3_label', 'Text', @en, N'Work & Casual Meetings'),
(@Spaces, N'tab_3_label', 'Text', @ar, N'العمل واللقاءات غير الرسمية'),
(@Spaces, N'panel_1_title', 'Text', @en, N'Dining & Shisha'),
(@Spaces, N'panel_1_title', 'Text', @ar, N'الطعام والأرجيلة'),
(@Spaces, N'panel_1_body', 'Text', @en, N'Placeholder description — elegant dining spaces with authentic Lebanese hospitality, paired with a curated shisha experience. Final copy to be provided by the client.'),
(@Spaces, N'panel_1_body', 'Text', @ar, N'نص مؤقت — أجواء طعام أنيقة تجمع بين الضيافة اللبنانية الأصيلة وتجربة أرجيلة مميزة. سيتم توفير النص النهائي من قبل العميل.'),
(@Spaces, N'panel_1_gallery_1_caption', 'Text', @en, N'Dining Area'),
(@Spaces, N'panel_1_gallery_1_caption', 'Text', @ar, N'منطقة الطعام'),
(@Spaces, N'panel_1_gallery_2_caption', 'Text', @en, N'Shisha Lounge'),
(@Spaces, N'panel_1_gallery_2_caption', 'Text', @ar, N'صالة الأرجيلة'),
(@Spaces, N'panel_1_gallery_3_caption', 'Text', @en, N'Evening Ambiance'),
(@Spaces, N'panel_1_gallery_3_caption', 'Text', @ar, N'أجواء مسائية'),
(@Spaces, N'panel_1_gallery_4_caption', 'Text', @en, N'More Photos'),
(@Spaces, N'panel_1_gallery_4_caption', 'Text', @ar, N'المزيد من الصور'),
(@Spaces, N'panel_2_title', 'Text', @en, N'Indoor & Outdoor Spaces'),
(@Spaces, N'panel_2_title', 'Text', @ar, N'أجواء داخلية وخارجية'),
(@Spaces, N'panel_2_body', 'Text', @en, N'Placeholder description — versatile venues for any gathering, with stunning ambiance inside and out. Final copy to be provided by the client.'),
(@Spaces, N'panel_2_body', 'Text', @ar, N'نص مؤقت — أجواء متعددة الاستخدامات تناسب كل تجمّع، بأجواء ساحرة داخلياً وخارجياً. سيتم توفير النص النهائي من قبل العميل.'),
(@Spaces, N'panel_2_gallery_1_caption', 'Text', @en, N'Indoor Salon'),
(@Spaces, N'panel_2_gallery_1_caption', 'Text', @ar, N'صالة داخلية'),
(@Spaces, N'panel_2_gallery_2_caption', 'Text', @en, N'Outdoor Terrace'),
(@Spaces, N'panel_2_gallery_2_caption', 'Text', @ar, N'تراس خارجي'),
(@Spaces, N'panel_2_gallery_3_caption', 'Text', @en, N'Garden Seating'),
(@Spaces, N'panel_2_gallery_3_caption', 'Text', @ar, N'جلسة حديقة'),
(@Spaces, N'panel_2_gallery_4_caption', 'Text', @en, N'More Photos'),
(@Spaces, N'panel_2_gallery_4_caption', 'Text', @ar, N'المزيد من الصور'),
(@Spaces, N'panel_3_title', 'Text', @en, N'Work & Casual Meetings'),
(@Spaces, N'panel_3_title', 'Text', @ar, N'العمل واللقاءات غير الرسمية'),
(@Spaces, N'panel_3_body', 'Text', @en, N'Placeholder description — a calm environment for studying, working, and informal gatherings. Final copy to be provided by the client.'),
(@Spaces, N'panel_3_body', 'Text', @ar, N'نص مؤقت — بيئة هادئة للدراسة والعمل واللقاءات غير الرسمية. سيتم توفير النص النهائي من قبل العميل.'),
(@Spaces, N'panel_3_gallery_1_caption', 'Text', @en, N'Quiet Corners'),
(@Spaces, N'panel_3_gallery_1_caption', 'Text', @ar, N'أركان هادئة'),
(@Spaces, N'panel_3_gallery_2_caption', 'Text', @en, N'Work-Friendly Seating'),
(@Spaces, N'panel_3_gallery_2_caption', 'Text', @ar, N'جلسات مناسبة للعمل'),
(@Spaces, N'panel_3_gallery_3_caption', 'Text', @en, N'Casual Meeting Tables'),
(@Spaces, N'panel_3_gallery_3_caption', 'Text', @ar, N'طاولات لقاءات غير رسمية'),
(@Spaces, N'panel_3_gallery_4_caption', 'Text', @en, N'More Photos'),
(@Spaces, N'panel_3_gallery_4_caption', 'Text', @ar, N'المزيد من الصور'),
(@Spaces, N'cta_label', 'Text', @en, N'Reserve a Table'),
(@Spaces, N'cta_label', 'Text', @ar, N'احجز طاولة');

COMMIT TRANSACTION;

SELECT p.PageName, COUNT(*) AS AttributeCount
FROM customer.page_attributes pa
JOIN customer.pages p ON p.Id = pa.PageId
GROUP BY p.PageName
ORDER BY p.PageName;
